const products = [
  {
    id:'1',
    name:'Airpad wireless bluetooth headphones',
    image:'/images/airpods.jpg',
    description: "Bluetooth technology lets you connect it with compatiable",
    brand:'Apple',
    category:"Electronics",
    price: 89.99,
    countInStock:3,
    rating:4.5,
    numReviews:4,
  },
  {
    id:'2',
    name:'Airpad wireless bluetooth headphones',
    image:'/images/airpods.jpg',
    description: "Bluetooth technology lets you connect it with compatiable",
    brand:'Apple',
    category:"Electronics",
    price: 89.99,
    countInStock:3,
    rating:4.5,
    numReviews:4,
  },
  {
    id:'3',
    name:'Airpad wireless bluetooth headphones',
    image:'/images/airpods.jpg',
    description: "Bluetooth technology lets you connect it with compatiable",
    brand:'Apple',
    category:"Electronics",
    price: 89.99,
    countInStock:3,
    rating:4.5,
    numReviews:4,
  },
  {
    id:'4',
    name:'Airpad wireless bluetooth headphones',
    image:'/images/airpods.jpg',
    description: "Bluetooth technology lets you connect it with compatiable",
    brand:'Apple',
    category:"Electronics",
    price: 89.99,
    countInStock:3,
    rating:4.5,
    numReviews:4,
  },
  {
    id:'5',
    name:'Airpad wireless bluetooth headphones',
    image:'/images/airpods.jpg',
    description: "Bluetooth technology lets you connect it with compatiable",
    brand:'Apple',
    category:"Electronics",
    price: 89.99,
    countInStock:3,
    rating:4.5,
    numReviews:4,
  },
  {
    id:'6',
    name:'Airpad wireless bluetooth headphones',
    image:'/images/airpods.jpg',
    description: "Bluetooth technology lets you connect it with compatiable",
    brand:'Apple',
    category:"Electronics",
    price: 89.99,
    countInStock:3,
    rating:4.5,
    numReviews:4,
  }
]